2022-12-19 16:26:51,263 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-19 16:27:41,493 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2022-12-19 16:31:03,278 -  nornir.core -     INFO -        run() - Running task 'napalm_get_example' with args {} on 1 hosts
2022-12-19 16:31:53,019 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-19 16:32:27,382 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-19 16:54:54,788 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-19 16:55:18,900 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-19 17:56:14,326 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-19 17:58:50,624 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2022-12-19 18:00:24,617 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-21 01:40:53,048 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-23 01:24:47,289 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2022-12-24 23:44:48,068 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-24 23:46:01,816 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-24 23:46:53,432 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-24 23:47:36,664 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-24 23:48:27,523 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-24 23:49:49,201 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-24 23:49:50,083 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.3.nornir_napalm_get_result_parsing.py", line 18, in nornir_napalm_get_example
    rprint(config.result)    #6
NameError: name 'config' is not defined

2022-12-24 23:50:41,512 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-24 23:50:42,148 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.3.nornir_napalm_get_result_parsing.py", line 19, in nornir_napalm_get_example
    rprint(config.result["get_config"]) #7
NameError: name 'config' is not defined

2022-12-24 23:51:01,493 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2022-12-24 23:51:02,381 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.3.nornir_napalm_get_result_parsing.py", line 20, in nornir_napalm_get_example
    rprint(config.result["get_config"]["running"])    #8
NameError: name 'config' is not defined

2022-12-24 23:52:13,846 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-24 23:52:34,710 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-25 03:26:45,740 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-25 03:30:22,717 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:30:52,170 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:31:42,991 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:32:48,212 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:33:43,082 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:35:07,786 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:36:06,379 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:37:01,159 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:44:05,664 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:44:35,461 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:45:11,598 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:46:02,436 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:46:55,958 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:47:25,303 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:48:01,747 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-26 01:48:28,256 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_structured_output_example' with args {} on 1 hosts
2022-12-27 13:44:29,179 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 13:44:31,225 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/.local/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/ios/ios.py", line 802, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2022-12-27 13:44:31,226 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_send_config_exmaple' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.4.nornir_napalm_send_config.py", line 9, in nornir_napalm_send_config_exmaple
    task.run(task=napalm_configure, filename="config_file.txt")
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2022-12-27 13:45:39,014 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 13:50:05,940 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_write_file_example' with args {} on 1 hosts
2022-12-27 13:50:51,239 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_write_file_example' with args {} on 1 hosts
2022-12-27 13:51:37,387 -  nornir.core -     INFO -        run() - Running task 'nornir_utils_write_file_example' with args {} on 1 hosts
2022-12-27 13:51:45,318 -  nornir.core -     INFO -        run() - Running task 'nornir_utils_write_file_example' with args {} on 1 hosts
2022-12-27 13:53:39,795 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 14:02:44,271 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 14:02:47,997 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/.local/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 43, in napalm_configure
    device.commit_config()
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/ios/ios.py", line 573, in commit_config
    raise ReplaceConfigException(msg)
napalm.base.exceptions.ReplaceConfigException: napalm-ios replace() requires Cisco 'archive' feature to be enabled

2022-12-27 14:02:47,998 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_send_config_exmaple' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.6.nornir_napalm_send_config_replace.py", line 9, in nornir_napalm_send_config_exmaple
    task.run(task=napalm_configure, filename=f"{task.host}", replace=True)
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2022-12-27 14:03:05,427 -  nornir.core -     INFO -        run() - Running task 'nornir_utils_write_file_example' with args {} on 1 hosts
2022-12-27 14:03:37,307 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 14:03:40,966 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/.local/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 43, in napalm_configure
    device.commit_config()
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/ios/ios.py", line 573, in commit_config
    raise ReplaceConfigException(msg)
napalm.base.exceptions.ReplaceConfigException: napalm-ios replace() requires Cisco 'archive' feature to be enabled

2022-12-27 14:03:40,967 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_send_config_exmaple' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.6.nornir_napalm_send_config_replace.py", line 9, in nornir_napalm_send_config_exmaple
    task.run(task=napalm_configure, filename=f"{task.host}", replace=True)
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2022-12-27 14:05:20,120 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 14:05:42,284 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 14:05:45,764 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/.local/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 43, in napalm_configure
    device.commit_config()
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/ios/ios.py", line 573, in commit_config
    raise ReplaceConfigException(msg)
napalm.base.exceptions.ReplaceConfigException: napalm-ios replace() requires Cisco 'archive' feature to be enabled

2022-12-27 14:05:45,765 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_send_config_exmaple' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.6.nornir_napalm_send_config_replace.py", line 9, in nornir_napalm_send_config_exmaple
    task.run(task=napalm_configure, filename=f"{task.host}", replace=True)
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2022-12-27 14:06:17,293 -  nornir.core -     INFO -        run() - Running task 'nornir_utils_write_file_example' with args {} on 1 hosts
2022-12-27 14:06:37,187 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 14:07:02,665 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 14:07:35,574 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 14:08:52,176 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 14:09:06,221 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/.local/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 43, in napalm_configure
    device.commit_config()
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/ios/ios.py", line 559, in commit_config
    output = self._commit_handler(cmd)
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/ios/ios.py", line 467, in wrapper
    return f(self, *args, **kwargs)
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/ios/ios.py", line 484, in _commit_handler
    output = self.device.send_command(cmd, expect_string=patterns)
  File "/home/majid/.local/lib/python3.10/site-packages/netmiko/utilities.py", line 596, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/majid/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 1691, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
Pattern not detected: '(?:[>##]\\s*$|.*all username.*confirm)' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



2022-12-27 14:09:06,222 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_send_config_exmaple' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.6.nornir_napalm_send_config_replace.py", line 9, in nornir_napalm_send_config_exmaple
    task.run(task=napalm_configure, filename=f"{task.host}", replace=True)
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2022-12-27 14:09:53,232 -  nornir.core -     INFO -        run() - Running task 'nornir_utils_write_file_example' with args {} on 1 hosts
2022-12-27 14:10:20,188 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 15:10:21,201 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 15:17:44,234 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 16:05:27,561 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 16:06:12,777 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 16:06:48,274 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 16:08:08,642 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-27 16:19:39,775 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-28 03:06:08,967 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-28 03:06:57,716 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-29 02:26:21,080 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-29 02:27:49,654 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_send_config_exmaple' with args {} on 1 hosts
2022-12-30 02:16:22,273 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2022-12-30 02:17:21,584 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2022-12-30 02:17:36,705 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2022-12-30 02:21:32,045 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_restore_with_send_config_replace' with args {} on 1 hosts
2022-12-30 02:26:35,256 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2022-12-30 02:29:01,739 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_restore_with_send_config_replace' with args {} on 1 hosts
2022-12-30 13:51:49,053 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2022-12-30 13:51:49,054 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_utils_backup_example' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.5.nornir_napalm_utils_backup_example.py", line 9, in nornir_napalm_utils_backup_example
    running_config=task.run(task=napalm_get, getters=["get_config"]["running"])
TypeError: list indices must be integers or slices, not str

2022-12-30 13:52:39,619 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 01:40:36,351 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 01:43:39,981 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_restore_with_send_config_replace' with args {} on 1 hosts
2023-01-01 04:25:52,750 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 04:25:53,944 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_utils_backup_example' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.7.nornir_napalm_replace_config_example.py", line 15, in nornir_napalm_utils_backup_example
    task.run(task=napalm_configure, filename=f"{task.host}", replace=True)
NameError: name 'napalm_configure' is not defined

2023-01-01 04:28:06,162 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 05:02:52,111 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 13:40:26,484 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:50:27,467 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:51:57,225 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:52:17,127 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:52:50,444 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:52:57,229 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:53:38,862 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:53:48,342 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:54:20,708 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:57:02,454 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:57:28,965 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:57:56,131 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 16:58:36,243 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 17:01:42,030 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 19:48:50,777 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 19:50:38,536 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-01 19:53:24,439 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_utils_backup_example' with args {} on 1 hosts
2023-01-03 01:51:43,464 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_replace_config_example' with args {} on 1 hosts
2023-01-03 01:52:24,760 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_replace_config_example' with args {} on 1 hosts
2023-01-03 01:53:13,389 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_replace_config_example' with args {} on 1 hosts
2023-01-03 13:47:18,208 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2023-01-03 13:56:40,983 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_compliance_validation_check' with args {} on 1 hosts
2023-01-03 13:56:41,796 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_validate' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/.local/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_validate.py", line 30, in napalm_validate
    r = device.compliance_report(
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/base/base.py", line 1800, in compliance_report
    return validate.compliance_report(
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/base/validate.py", line 237, in compliance_report
    assert isinstance(validation_source, list), validation_source
AssertionError: {'get_ntp_servers': {'1.2.3.4': {}, '5.6.7.8': {}}}

2023-01-03 13:56:41,796 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_compliance_validation_check' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.8.nornir_napalm_compliance_validation.py", line 10, in nornir_napalm_compliance_validation_check
    result = task.run(task=napalm_validate, src="ntp.yaml")
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_validate (failed)


2023-01-03 13:57:46,632 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_compliance_validation_check' with args {} on 1 hosts
2023-01-03 13:58:59,607 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_compliance_validation_check' with args {} on 1 hosts
2023-01-03 13:59:42,913 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_compliance_validation_check' with args {} on 1 hosts
2023-01-03 14:00:15,710 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_compliance_validation_check' with args {} on 1 hosts
2023-01-03 14:00:43,445 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_compliance_validation_check' with args {} on 1 hosts
2023-01-03 14:42:12,082 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_compliance_validation_check' with args {} on 1 hosts
2023-01-03 14:42:12,870 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_validate' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/.local/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_validate.py", line 30, in napalm_validate
    r = device.compliance_report(
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/base/base.py", line 1800, in compliance_report
    return validate.compliance_report(
  File "/home/majid/.local/lib/python3.10/site-packages/napalm/base/validate.py", line 237, in compliance_report
    assert isinstance(validation_source, list), validation_source
AssertionError: {'get_ntp_servers': {'1.2.3.4': {}, '5.6.7.8': {}}}

2023-01-03 14:42:12,871 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_compliance_validation_check' failed with traceback:
Traceback (most recent call last):
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/majid/devnet/pyhton_nornir/2023/5.nornir_napalm/5.8.nornir_napalm_compliance_validation.py", line 8, in nornir_napalm_compliance_validation_check
    task.run(task=napalm_validate, src="ntp.yaml")
  File "/home/majid/.local/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_validate (failed)


2023-01-03 14:42:26,451 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_compliance_validation_check' with args {} on 1 hosts
2023-01-05 01:59:18,307 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2023-01-05 02:05:47,584 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_compliance_validation_check' with args {} on 1 hosts
2023-01-05 02:06:53,881 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_compliance_validation_check' with args {} on 1 hosts
2024-04-17 00:34:23,094 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 00:35:08,119 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 00:36:04,702 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 00:38:51,311 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 00:41:09,606 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 00:42:05,316 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 00:42:25,431 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 01:13:36,307 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 01:14:26,521 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 01:18:31,589 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 01:18:40,932 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 01:18:41,465 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 43, in napalm_get
    method = getattr(device, getter)
             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IOSDriver' object has no attribute 'get_cdp_neighbors'

2024-04-17 01:18:41,467 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/testdir/devnet/pyhton_nornir/2023/5.nornir_napalm/5.1.nornir_napalm_get_commands.py", line 9, in nornir_napalm_get_example
    task.run(task=napalm_get, getters=["get_cdp_neighbors"])
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_get (failed)


2024-04-17 02:06:55,806 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 02:10:35,029 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:13:53,317 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:15:25,249 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:35:02,207 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:40:36,567 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:41:38,236 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:42:14,360 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:42:33,901 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:43:01,888 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:44:50,513 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:50:07,707 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:51:54,970 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:52:17,289 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:52:33,885 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:53:00,830 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 02:53:23,316 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:06:51,075 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:09:15,163 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:09:27,319 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:09:37,247 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:09:58,744 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:10:04,162 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:10:37,641 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:10:58,753 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:11:02,148 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:11:26,476 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:14:01,638 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:14:10,257 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:15:51,767 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:16:15,395 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:16:52,204 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:17:05,059 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:17:19,013 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:17:47,977 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:18:03,718 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:18:21,346 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:18:30,868 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:18:46,815 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:18:54,853 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:19:05,314 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:19:43,562 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:21:14,636 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:22:44,780 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:23:11,055 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:24:24,532 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:24:39,678 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:25:06,015 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:28:05,202 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:28:39,895 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:29:08,711 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:29:40,622 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:29:53,397 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:30:07,093 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 03:30:26,837 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:29:56,794 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:34:42,408 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:35:11,038 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:43:32,406 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:44:34,506 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:47:11,814 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:48:06,027 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:49:59,998 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:50:21,487 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:51:38,133 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:53:23,363 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:55:30,627 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 04:55:40,449 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:21:32,428 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:23:10,231 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:24:06,065 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:37:01,776 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:46:45,142 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:49:02,912 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:50:17,421 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:50:43,026 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:51:03,684 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:51:21,080 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:51:45,826 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:52:37,596 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:52:45,046 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:53:01,138 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:54:07,046 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:56:15,297 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:56:27,047 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:57:21,430 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:57:42,048 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:57:51,831 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:58:18,001 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:58:43,045 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:59:10,839 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 05:59:40,877 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:00:24,151 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:00:49,943 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:01:43,507 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:01:57,854 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:02:19,055 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:02:59,721 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:04:59,852 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:05:22,056 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:05:44,920 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:05:54,168 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:06:17,852 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:06:29,135 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:07:01,486 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:07:45,768 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:08:08,473 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:08:22,264 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:08:29,943 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:08:38,099 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:08:46,604 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:09:01,763 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:09:22,218 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:09:49,189 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:09:58,570 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:10:16,015 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:16:18,128 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:17:09,108 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:17:26,390 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:17:53,465 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:18:02,868 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:18:50,505 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:18:59,518 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:19:09,624 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:19:31,123 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:19:47,229 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:20:00,207 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:20:09,941 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:20:45,660 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:21:39,052 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:21:47,642 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:23:20,188 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:23:30,212 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1137, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python3/dist-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
           ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
                            ^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 114, in _netmiko_open
    self._netmiko_device = ConnectHandler(
                           ^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 488, in __init__
    self._open()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 493, in _open
    self.establish_connection()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1159, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 10.5.48.88:22



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/ios/ios.py", line 173, in open
    self.device = self._netmiko_open(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 123, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 10.5.48.88

2024-04-17 06:23:30,212 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/testdir/devnet/pyhton_nornir/2023/5.nornir_napalm/5.1.nornir_napalm_get_commands.py", line 9, in nornir_napalm_get_example
    task.run(task=napalm_get, getters=["get_optics"])
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_get (failed)


2024-04-17 06:23:44,070 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:23:54,096 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1137, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python3/dist-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
           ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
                            ^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 114, in _netmiko_open
    self._netmiko_device = ConnectHandler(
                           ^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 488, in __init__
    self._open()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 493, in _open
    self.establish_connection()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1159, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 10.5.48.88:22



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/ios/ios.py", line 173, in open
    self.device = self._netmiko_open(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 123, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 10.5.48.88

2024-04-17 06:23:54,097 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/testdir/devnet/pyhton_nornir/2023/5.nornir_napalm/5.1.nornir_napalm_get_commands.py", line 9, in nornir_napalm_get_example
    task.run(task=napalm_get, getters=["get_facts"])
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_get (failed)


2024-04-17 06:23:59,872 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:24:09,879 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1137, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python3/dist-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
           ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
                            ^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 114, in _netmiko_open
    self._netmiko_device = ConnectHandler(
                           ^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 488, in __init__
    self._open()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 493, in _open
    self.establish_connection()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1159, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 10.5.48.88:22



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/ios/ios.py", line 173, in open
    self.device = self._netmiko_open(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 123, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 10.5.48.88

2024-04-17 06:24:09,880 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/testdir/devnet/pyhton_nornir/2023/5.nornir_napalm/5.1.nornir_napalm_get_commands.py", line 9, in nornir_napalm_get_example
    task.run(task=napalm_get, getters=["get_facts"])
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_get (failed)


2024-04-17 06:24:25,462 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:24:35,509 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1137, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python3/dist-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
           ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
                            ^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 114, in _netmiko_open
    self._netmiko_device = ConnectHandler(
                           ^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 488, in __init__
    self._open()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 493, in _open
    self.establish_connection()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1159, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 10.5.48.88:22



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/ios/ios.py", line 173, in open
    self.device = self._netmiko_open(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 123, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 10.5.48.88

2024-04-17 06:24:35,510 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/testdir/devnet/pyhton_nornir/2023/5.nornir_napalm/5.1.nornir_napalm_get_commands.py", line 9, in nornir_napalm_get_example
    task.run(task=napalm_get, getters=["get_interfaces"])
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_get (failed)


2024-04-17 06:24:46,208 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:24:56,222 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1137, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python3/dist-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
           ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
                            ^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 114, in _netmiko_open
    self._netmiko_device = ConnectHandler(
                           ^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 488, in __init__
    self._open()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 493, in _open
    self.establish_connection()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1159, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 10.5.48.88:22



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/ios/ios.py", line 173, in open
    self.device = self._netmiko_open(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 123, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 10.5.48.88

2024-04-17 06:24:56,222 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/testdir/devnet/pyhton_nornir/2023/5.nornir_napalm/5.1.nornir_napalm_get_commands.py", line 9, in nornir_napalm_get_example
    task.run(task=napalm_get, getters=["get_optics"])
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_get (failed)


2024-04-17 06:25:19,433 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:25:29,443 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1137, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python3/dist-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
           ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
                            ^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 114, in _netmiko_open
    self._netmiko_device = ConnectHandler(
                           ^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 488, in __init__
    self._open()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 493, in _open
    self.establish_connection()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1159, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 10.5.48.88:22



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/ios/ios.py", line 173, in open
    self.device = self._netmiko_open(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 123, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 10.5.48.88

2024-04-17 06:25:29,443 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/testdir/devnet/pyhton_nornir/2023/5.nornir_napalm/5.1.nornir_napalm_get_commands.py", line 9, in nornir_napalm_get_example
    task.run(task=napalm_get, getters=["get_optics"])
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_get (failed)


2024-04-17 06:26:04,142 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:26:14,156 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1137, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python3/dist-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
           ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 358, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
                            ^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 114, in _netmiko_open
    self._netmiko_device = ConnectHandler(
                           ^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 488, in __init__
    self._open()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 493, in _open
    self.establish_connection()
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 1159, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.exceptions.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 10.5.48.88:22



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/ios/ios.py", line 173, in open
    self.device = self._netmiko_open(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 123, in _netmiko_open
    raise ConnectionException("Cannot connect to {}".format(self.hostname))
napalm.base.exceptions.ConnectionException: Cannot connect to 10.5.48.88

2024-04-17 06:26:14,157 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/testdir/devnet/pyhton_nornir/2023/5.nornir_napalm/5.1.nornir_napalm_get_commands.py", line 9, in nornir_napalm_get_example
    task.run(task=napalm_get, getters=["get_optics"])
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_get (failed)


2024-04-17 06:27:41,010 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:32:36,833 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:32:51,408 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:33:35,819 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:33:40,477 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:33:57,002 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:34:08,822 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:34:17,761 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:34:51,948 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:35:20,348 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:35:23,249 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:35:59,293 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:39:18,086 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:39:26,595 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:39:32,432 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:39:40,346 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:39:58,474 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:40:24,164 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:41:05,168 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:41:18,086 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:41:35,852 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:41:47,684 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:42:07,083 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:42:21,784 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:42:34,557 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:42:40,512 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:43:28,130 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:43:43,356 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:43:47,215 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:44:15,487 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:44:23,254 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:44:40,339 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:44:52,523 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:45:36,152 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:48:10,790 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 1 hosts
2024-04-17 06:48:22,478 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:48:53,659 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:49:01,696 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-17 06:49:33,176 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:50:01,745 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:50:15,689 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:50:44,208 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:50:58,023 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:51:27,019 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:51:35,682 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:51:47,651 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:51:55,015 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:52:15,756 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:52:26,949 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:53:47,169 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:53:57,300 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:54:08,755 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:54:21,704 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:54:29,839 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:54:39,945 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:54:49,300 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:54:57,323 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:55:10,200 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:55:23,833 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:55:34,411 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:56:08,658 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:56:31,104 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:56:48,681 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:56:59,124 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:57:05,843 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:57:40,408 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:57:54,097 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:58:18,587 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:58:36,594 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:59:02,704 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 06:59:41,165 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:00:09,046 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:00:24,731 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:00:37,670 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:01:32,271 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:01:48,306 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:02:52,551 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:03:16,140 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:03:29,044 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:03:40,006 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:03:57,203 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:04:09,851 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:04:20,231 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:04:32,413 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:04:40,171 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:05:28,070 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:06:15,007 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:07:55,748 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:08:04,887 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-17 07:10:56,334 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:11:15,264 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:11:47,097 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:12:01,500 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:12:10,921 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:14:26,486 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:15:02,493 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:15:15,152 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:15:24,900 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:16:33,136 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:16:53,560 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:17:19,192 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:17:27,958 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:17:40,185 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:18:00,555 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:18:24,093 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:18:35,884 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:18:47,822 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:19:06,897 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:19:21,190 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:19:30,590 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:19:45,953 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:19:54,367 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:20:08,168 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:20:30,777 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:20:54,503 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:21:16,537 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:22:17,690 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:22:33,906 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:23:00,334 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:23:42,203 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:24:15,348 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:24:29,726 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:25:38,875 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:26:31,846 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:26:38,723 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:27:46,527 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:28:06,213 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:29:17,630 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:29:29,777 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:29:51,629 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:33:54,029 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:34:38,363 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:34:46,053 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:34:58,166 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:35:45,595 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:36:22,374 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:36:30,380 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:36:55,014 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:37:00,492 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:37:09,671 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:37:42,892 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:37:54,598 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:38:21,045 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:38:37,848 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:38:47,688 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:39:00,929 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:39:09,122 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:39:20,955 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:39:43,400 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:39:56,587 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:40:12,186 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:40:35,553 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:41:13,725 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:41:29,503 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:43:47,554 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:44:08,482 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:44:42,381 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:44:52,621 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:45:36,930 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:45:51,630 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:46:08,507 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:46:43,037 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:46:53,180 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:47:15,634 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:47:27,246 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:47:33,756 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:47:47,462 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:48:07,136 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:51:22,777 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:51:31,259 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:51:40,975 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:51:53,296 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:52:27,662 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:52:43,144 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:53:01,531 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:53:24,339 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:53:33,705 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:54:28,138 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:55:26,179 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:55:45,318 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 2 hosts
2024-04-17 07:56:51,545 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 3 hosts
2024-04-17 07:57:03,863 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 3 hosts
2024-04-17 07:57:15,018 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_cli_commands_example' with args {} on 3 hosts
2024-04-18 04:33:38,445 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-18 04:33:38,452 - nornir.core.task -    ERROR -      start() - Host 'BHQ-B-6F-SW': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/ios/ios.py", line 173, in open
    self.device = self._netmiko_open(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 114, in _netmiko_open
    self._netmiko_device = ConnectHandler(
                           ^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 349, in __init__
    raise ValueError("Either ip or host must be set")
ValueError: Either ip or host must be set

2024-04-18 04:33:38,452 - nornir.core.task -    ERROR -      start() - Host 'BHQ-B-6F-SW': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/Nornir/2023/5.nornir_napalm/5.1.nornir_napalm_get_commands.py", line 12, in nornir_napalm_get_example
    task.run(task=napalm_get, getters=[g])
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_get (failed)


2024-04-18 04:33:38,452 - nornir.core.task -    ERROR -      start() - Host 'BHQ-B-9F-SW': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 57, in open
    connection.open()
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/ios/ios.py", line 173, in open
    self.device = self._netmiko_open(
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/base.py", line 114, in _netmiko_open
    self._netmiko_device = ConnectHandler(
                           ^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py", line 399, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/netmiko/base_connection.py", line 349, in __init__
    raise ValueError("Either ip or host must be set")
ValueError: Either ip or host must be set

2024-04-18 04:33:38,452 - nornir.core.task -    ERROR -      start() - Host 'BHQ-B-9F-SW': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/Nornir/2023/5.nornir_napalm/5.1.nornir_napalm_get_commands.py", line 12, in nornir_napalm_get_example
    task.run(task=napalm_get, getters=[g])
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_get (failed)


2024-04-18 04:35:48,638 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-18 04:36:51,193 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-18 04:38:37,026 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-18 04:51:18,915 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 2 hosts
2024-04-18 05:00:29,210 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 3 hosts
2024-04-18 06:03:15,686 -  nornir.core -     INFO -        run() - Running task 'nornir_napalm_get_example' with args {} on 1 hosts
2024-04-18 06:03:15,688 - nornir.core.task -    ERROR -      start() - Host 'BHA-02-R2-Sw1': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 32, in napalm_get
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/kali/.local/lib/python3.11/site-packages/nornir_napalm/plugins/connections/__init__.py", line 55, in open
    network_driver = get_network_driver(platform)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/napalm/base/__init__.py", line 99, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "hpe comware". Is the library installed?

2024-04-18 06:03:15,689 - nornir.core.task -    ERROR -      start() - Host 'BHA-02-R2-Sw1': task 'nornir_napalm_get_example' failed with traceback:
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/Nornir/2023/5.nornir_napalm/5.1.nornir_napalm_get_commands.py", line 12, in nornir_napalm_get_example
    task.run(task=napalm_get, getters=[g])
  File "/home/kali/.local/lib/python3.11/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_get (failed)


